name: Compile MM addon
on:
  - push
  - pull_request

env:
  HL2SDKCS2: ${{ github.workspace }}/mm-cs2-scrim/sdk
  MMSOURCE_DEV: ${{ github.workspace }}/mm-cs2-scrim/metamod-source

jobs:
  build:
    runs-on: windows-latest
       
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: mm-cs2-scrim
          submodules: recursive

      - name: Checkout Metamod
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/metamod-source
          ref: master
          path: mmsource-2.0
          submodules: recursive
  
      - name: Checkout AMBuild
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        run: |
          cd ambuild && python setup.py install && cd ..

      - name: Build
        working-directory: mm-cs2-scrim
        shell: bash
        run: |
          mkdir build && cd build
          python ../configure.py --enable-optimize --symbol-files --sdks cs2 --targets x86_64
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}
          path: cs2scrim/build/package